### ISSUE TITLE
Deadlock in JSONUtil.httpGetJSON

### ISSUE THREAD

**Issue by ansell** [ansell/csvsum#24]
Deadlock occurred with the following stacktrace:

```
"main" #1 prio=5 os_prio=0 tid=0x00007fd18400d000 nid=0x238a waiting on condition [0x00007fd18d609000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c56b9ea8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:377)
	at org.apache.http.pool.AbstractConnPool.access$200(AbstractConnPool.java:67)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:243)
	- locked <0x000000077a1a80d8> (a org.apache.http.pool.AbstractConnPool$2)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:191)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:282)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:269)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
	at org.apache.http.impl.client.cache.CachingExec.callBackend(CachingExec.java:593)
	at org.apache.http.impl.client.cache.CachingExec.handleCacheMiss(CachingExec.java:357)
	at org.apache.http.impl.client.cache.CachingExec.execute(CachingExec.java:276)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.ansell.csv.util.JSONUtil.openStreamForURL(JSONUtil.java:234)
	at com.github.ansell.csv.util.JSONUtil.openStreamForURL(JSONUtil.java:222)
	at com.github.ansell.csv.util.JSONUtil.httpGetJSON(JSONUtil.java:83)
```

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

httpcore version 4.4.6

httpclient version 4.5.3

**Comment by ansell** [comment]
Fixed by using the timeout versions, that use an interruptible path in AbstractConnPool
